import json
import sys
from datetime import datetime
import config
from utils.logger import get_logger

logger = get_logger('custom_report')

# The list of tickers requested - use config for core holdings
TARGET_TICKERS = config.PORTFOLIO_TICKERS + [
    "VRT", "CEG", "GEV", "ETN", "ASML", "CCJ", "HWM", "HEI", 
    "HALO", "NVT", "NXST", "CRUS", "HUBB", "QXO", "MRVL", "TSM"
]

def generate_report():
    try:
        with open("all_stocks.json", "r") as f:
            data = json.load(f)
        stocks = data.get("stocks", {})
    except FileNotFoundError:
        logger.error("Error: all_stocks.json not found.")
        return

    report_data = []
    
    for ticker in TARGET_TICKERS:
        stock = stocks.get(ticker)
        if stock:
            report_data.append(stock)
        else:
            # Create a dummy entry if not found, to show it's missing
            report_data.append({
                "ticker": ticker,
                "name": "N/A",
                "score": 0,
                "grade": "N/A",
                "moonshot_score": 0,
                "technical_score": 0,
                "growth_score": 0,
                "sector": "Unknown"
            })

    # Sort by Score High to Low
    report_data.sort(key=lambda x: x.get("score", 0), reverse=True)

    # HTML Generation
    date_str = datetime.now().strftime('%Y-%m-%d')
    html = f"""
    <html>
    <head>
    <style>
        body {{ font-family: Arial, sans-serif; color: #333; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #f8f9fa; font-weight: bold; color: #2c3e50; }}
        tr:hover {{ background-color: #f1f1f1; }}
        .grade-A {{ color: #27ae60; font-weight: bold; }}
        .grade-B {{ color: #2980b9; font-weight: bold; }}
        .grade-C {{ color: #f39c12; font-weight: bold; }}
        .grade-D {{ color: #c0392b; font-weight: bold; }}
        .moonshot {{ color: #8e44ad; font-weight: bold; }}
        .footer {{ margin-top: 30px; font-size: 0.8em; color: #7f8c8d; }}
    </style>
    </head>
    <body>
    <h1>InvestIQ Custom Report: Selected Holdings</h1>
    <p><strong>Date:</strong> {date_str}</p>
    
    <table>
        <thead>
            <tr>
                <th>Ticker</th>
                <th>Name</th>
                <th>Score</th>
                <th>Grade</th>
                <th>Moonshot %</th>
                <th>Tech Score</th>
                <th>Growth Score</th>
            </tr>
        </thead>
        <tbody>
    """

    for s in report_data:
        grade = s.get("grade", "N/A")
        grade_class = f"grade-{grade}" if grade in ["A", "B", "C", "D"] else ""
        
        moonshot = s.get("moonshot_score", 0)
        moonshot_display = f"{moonshot}%" if moonshot > 0 else "-"
        
        html += f"""
            <tr>
                <td><strong>{s.get("ticker")}</strong></td>
                <td>{s.get("name")}</td>
                <td>{s.get("score")}</td>
                <td class="{grade_class}">{grade}</td>
                <td class="moonshot">{moonshot_display}</td>
                <td>{s.get("technical_score")}</td>
                <td>{s.get("growth_score")}</td>
            </tr>
        """

    html += """
        </tbody>
    </table>
    <div class="footer">
        Generated by Danswiz (OpenClaw) from InvestIQ Database.
    </div>
    </body>
    </html>
    """

    filename = "custom_ratings_report.html"
    with open(filename, "w") as f:
        f.write(html)
    
    logger.info(f"Report generated: {filename}")
    print(f"✅ Report generated: {filename}")

if __name__ == "__main__":
    generate_report()
